### ISSUE TITLE
Incorrect Recommendation for conservationists

### ISSUE THREAD

**Issue by JagaRamesh** [cschellenberger/Biodiversity-Capstone#1]
You recommended the additional conservation for reptiles.

Through Chi-square test, we only proved that the protection_percentage of Reptiles(6.4%) and Mammals (17%) are significantly different.
Based on the percentage_protection, still Mammals (17%) and Birds(15%) are more protected and hence those species are highly endangered.

**Comment by cschellenberger** [comment]
Hello Jaga,

Thank you for your feedback and I completely understand your analysis. I interpreted the data differently, and probably incorrectly. In finding that the reptiles were significantly different with 6.4% I concluded that researchers had not adequately identified enough species requiring protection. I can see now that this conclusion is contrived and based on data that was not presented in the dataset.
