### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [cschellenberger/Biodiversity-Capstone#2]
Accurate coding! Good work with the powerpoint presentation!

The powerpoint slides are sequenced well and communicated the information effectively. 
The matplotlib plots are neat with proper title, xlabel and ylabel defined.  
The slides are well laid out with data and summaries.

I noticed that the recommendation for conservationists is incorrect. So I created an issue for the same.

The sample size calculation and the conclusion for "Foot and mouth disease analysis" is accurate.

Overall Great Job! KEEP IT UP!!

**Comment by cschellenberger** [comment]
I appreciate the time taken to review my analysis and give appropriate feedback.
